
pipeline {
    agent {
        label ("aws-deploy")
    }
    // environment {
    //     DOCKERHUB_CREDENTIALS = credentials('dockerhub')
    // }
    stages {
        stage('Test-Auth-Binaries') {
         agent {
            docker {
              image 'golang:alpine'
              args '-u root:root'
            }
            }
            steps {
                sh '''
                cd weatherapp/auth/src/main
                go build
                ls -latr
                cd -
                '''
            }
        }

        // stage('Hello2') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }

        // stage('Hello3') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }

        // stage('Hello4') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }

        // stage('Hello') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }

        // stage('Hello') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }

        // stage('Hello') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }

        // stage('Hello') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }

        // stage('Hello') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }

        // stage('Hello') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }

        // stage('Hello') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }

        // stage('Hello') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }

        // stage('Hello') {
        //     steps {
        //         sh '''
        //         ls 
        //         pwd
        //         '''
        //     }
        // }
    }
}


             

